### ISSUE TITLE
v2: tracking issue

### ISSUE THREAD

**Issue by robbielyman** [ryleelyman/seamstress#130]
# feature parity

seamstress v2 should be able to do essentially everything seamstress v1 can do unless there are good reasons not to.
here are some parts of seamstress v1 and their current status in v2.
- [x] logging to `/tmp/seamstress.log`. unclear to me what should happen here—increased testing? crashing with a stack trace? logging to a file?
- [ ] command line args. most of these should be migrated to `config.lua`
- [x] `metros`
- [x] `clocks`
- [ ] listening for Lua over UDP (`socket.zig`)
- [ ] GUI window
- [ ] 2D drawing API
- [x] hot reload
- [x] OSC (although needs to be migrated to the new style)
- [x] monome devices (ditto)
- [ ] params / mapping system

here are some things that seamstress v2 should do that seamstress v1 cannot
- [ ] ergonomic, idiomatic (i.e. not native) but customizable UI objects (buttons, dials, sliders, textboxes, etc)
- [ ] 3D drawing API (loading models?? textures?? custom shaders)
- [ ] ergonomic key + mouse handling, similar to 
- [ ] beautiful sufficient-unto-itself, customizable TUI operation
- [ ] (make GUI windows optional)
- [ ] Windows??
- [ ] crow??
- [ ] softcut??
- [ ] audio-reactivity in general
- [ ] deeper audio stuff???
